apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: flask-service
  labels:
    svc: flask-service
spec:
  ports:
  - name: flask-svc
    port: 5001
    targetPort: 5001
  selector:
    app: flask-app
