apiVersion: v1
kind: Service
metadata:
  name: promkafkawriter-metrics
  labels:
    iks-metric: http-metrics
spec:
  ports:
    - name: iks-metric
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: promkafkawriter
